Abraca-data/abracadata/abracadata/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^search/', include('search.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.home),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Abraca-data/abracadata/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'


urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

Abraca-data/abracadata/search/urls.py
from django.conf.urls import url
from . import views

app_name = 'search'

urlpatterns = [
    url(r'^$', views.search_list, name="list"),
    url(r'^(?P<slug>[\w-]+)/$', views.search_detail, name="detail"),
]

Abraca-data/abracadata/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

Abraca-data/abracadata/search/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
import django.utils.timezone as tz
# Create your models here.


class Pet(models.Model):
    name = models.CharField(max_length=45, null=True)
    age = models.IntegerField(null=False)
    sex = models.IntegerField(null=False)
    spayed = models.BooleanField()
    color = models.CharField(max_length=45, null=True)
    fostered = models.BooleanField()
    acquired_date = models.DateField(null=False, default=tz.now())
    breed = models.CharField(max_length=50, null=False, default='Unknown')
    image = models.TextField(default='default.jpeg')
    slug = models.SlugField(default='unknown')
    description = models.TextField(default=' ')
    pet_id = models.CharField(max_length=8, null=False, default='No ID')

    def __str__(self):
        return self.name

    def get_sex(self):
        if self.sex == 1:
            return 'Female'
        elif self.sex == 0:
            return 'Male'
        else:
            return 'Unknown'

    def get_age(self):
        if self.age < 0:
            return 'Invalid age'

        years = self.age / 12
        months = self.age % 12

        if years == 1 and months == 1:
            return str(years) + ' year ' + str(months) + ' month'
        elif years == 1:
            return str(years) + ' year ' + str(months) + ' months'
        elif months == 1:
            return str(years) + ' years ' + str(months) + ' month'
        else:
            return str(years) + ' years ' + str(months) + ' months'


    def get_spayed(self):
        if self.spayed:
            return 'yes'
        else:
            return 'no'

    def get_fostered(self):
            if self.fostered:
                return 'yes'
            else:
                return 'no'

Abraca-data/abracadata/abracadata/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')

Abraca-data/abracadata/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('search:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('search:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('search:list')

Abraca-data/abracadata/search/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from slugify import slugify
from django.shortcuts import render
from .models import Pet
from bs4 import BeautifulSoup
import requests


pet_ids = set()


def search_list(request):
    savepets()
    pets = Pet.objects.all().order_by('acquired_date')
    return render(request, 'search/search_list.html', {'pets': pets})


def get_month(month):
    switcher = {
        "January": '1',
        "February": '2',
        "March": '3',
        "April": '4',
        "May": '5',
        "June": '6',
        "July": '7',
        "August": '8',
        "September": '9',
        "October": '10',
        "November": '11',
        "December": '12'
    }
    return switcher.get(month, '1')


def savepets():
    source = requests.get('https://www.talgov.com/animals/kennel-dogs.aspx').text
    soup = BeautifulSoup(source, 'lxml')
    pets = soup.find('table', class_='table_data')

    for pet_data in pets.tbody.find_all('td', valign='top'):
        pet_description = str(pet_data).split('<br/>')[1]
        parsebycommas = pet_description.split(',')
        parsebyspace = parsebycommas[0].split(' ')
        sex_description = parsebyspace[len(parsebyspace) - 1]
        spayed_description = parsebyspace[len(parsebyspace) - 2]
        breed = parsebycommas[1].split('.')[0][1:]
        color = parsebycommas[1].split('generally ')[1].split(' in')[0]
        pet_name_text = pet_data.strong.text.split('-')[0]
        petid_text = pet_data.strong.text.split('-')[1]
        pet_name = pet_name_text[0:len(pet_name_text)]
        petid = petid_text[1:len(petid_text)+1]
        pet_image_link = 'http://www.petharbor.com:80/get_image.asp?RES=thumb&ID=' + str(petid) + '&LOCATION=TLLS'
        years = int(parsebycommas[2].split(' ')[8])

        if parsebycommas[2].split(' ')[11].isnumeric():
            months = int(parsebycommas[2].split(' ')[11])
        else:
            months = 0

        age = years*12 + months

        if sex_description == 'female':
            sex = 1
        elif sex_description == 'male':
            sex = 0
        else:
            sex = -1

        if spayed_description is not 'unaltered':
            spayed = True
        elif spayed_description == 'spayed' or spayed_description == 'neutered':
            spayed = False
        else:
            spayed = None

        wordset = set()
        for stri in pet_description.split(' '):
            wordset.add(stri)

        if 'foster' in wordset:
            fostered = True
        else:
            fostered = False

        date_list = parsebycommas[2].split(' ')
        day = date_list[len(date_list) - 1]
        month = date_list[len(date_list) - 2]

        month_num = get_month(month)

        year = parsebycommas[3].split('.')[0][1:]
        acquired_date = year + '-' + month_num + '-' + day

        if petid != 'No ID':
            if petid not in pet_ids:
                pet_object = Pet()
                pet_object.name = pet_name
                pet_object.age = age
                pet_object.sex = sex
                pet_object.spayed = spayed
                pet_object.color = color
                pet_object.fostered = fostered
                pet_object.description = pet_description
                pet_object.acquired_date = acquired_date
                pet_object.pet_id = petid
                pet_object.slug = slugify(pet_object.name)
                pet_object.image = pet_image_link
                pet_object.breed = breed
                pet_ids.add(petid)
                pet_object.save()
        else:
            pet_object = Pet()
            pet_object.name = pet_name
            pet_object.age = age
            pet_object.sex = sex
            pet_object.spayed = spayed
            pet_object.color = color
            pet_object.fostered = fostered
            pet_object.description = pet_description
            pet_object.pet_id = petid
            pet_object.breed = breed
            pet_object.slug = slugify(pet_object.name)
            pet_object.image = pet_image_link
            pet_ids.add(petid)
            pet_object.save()


def search_detail(request, slug):
    pet = Pet.objects.get(slug=slug)
    return render(request, 'search/search_detail.html', {'pet': pet})

Abraca-data/abracadata/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log In</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Log In">
    </form>
{% endblock %}

Abraca-data/abracadata/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Sign Up</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Sign Up">
    </form>
{% endblock %}

Abraca-data/abracadata/search/templates/search/search_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="search-detail">
    <div class="search">
        <img src="{{ pet.image }}" style="height:20%; width:20%;"/>
        <h2>{{pet.name}}</h2>
        <p>Breed: {{pet.breed}}</p>
        <p>Age: {{pet.get_age}}</p>
        <p>Acquired: {{pet.acquired_date}}</p>
        <p>Spayed/Neutered: {{pet.get_spayed}}</p>
        <p>Size: {{pet.size}}</p>
        <p>Color: {{pet.color}}</p>
        <p>Fostered: {{pet.get_fostered}}</p>
        <p>Sex: {{pet.get_sex}}</p>
        <p>Description: {{pet.description}}</p>
    </div>
</div>
{% endblock %}

Abraca-data/abracadata/search/templates/search/search_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <p>Adopt!</p>
    <div class="pets">
        {% for pet in pets %}
            <div class="pet">
                <img src="{{ pet.image }}" style="height:20%; width:20%;"/>
                <h2><a href="{% url 'search:detail' slug=pet.slug %}">{{pet.name}}</a></h2>
                <p>Sex: {{pet.get_sex}}</p>
                <p>Age: {{pet.get_age}}</p>
                <p>Breed: {{pet.breed}}</p>
                <p>Spayed/Neutered: {{pet.spayed}}</p>
                <p>Size: {{pet.size}}</p>
                <p>Color: {{pet.color}}</p>
                <p>Fostered: {{pet.fostered}}</p>
                <p>Acquired Date: {{pet.acquired_date}}</p>
                <p>Description: {{pet.description}}</p>
                <p>Pet ID: {{pet.pet_id}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

Abraca-data/abracadata/templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>About Page</title>
    </head>
    <body>
        <h1>This is the about page</h1>
        <p>Hello!</p>
    </body>
</html>

Abraca-data/abracadata/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Search Page</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'search:list' %}"><img class="logo" src="{% static 'dog-logo.jpeg' %}" style="height: 10%; width:10%;"/> </a></h1>
            <nav>
                <ul>
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">
                                Log out
                            </button>
                        </form>
                    </li>
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

Abraca-data/abracadata/templates/home.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Home Page</title>
    </head>
    <body>
        <h1>This is the homepage</h1>
        <p>Welcome!</p>
    </body>
</html>